# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-arm64
absl-py
aiohttp
aiosignal
alembic
altair
annotated-types
ansi2html
anyio
appnope
argon2-cffi
argon2-cffi-bindings
arrow
asttokens
astunparse
async-timeout
attrs=23.1.0
backcall
bcrypt
beautifulsoup4
binaryornot
black=23.9.1
bleach
blinker
bokeh
bottleneck
bzip2
ca-certificates
cachelib
cachetools
certifi
cffi
chardet
charset-normalizer
click
cloudpickle
comm
contourpy
cookiecutter
coverage
cycler
cython
dash
dash-core-components
dash-html-components
dash-table
dask
dataprep
debugpy
decorator
defusedxml
dnspython
email-validator
entrypoints
environs
executing
factory-boy
faker
fastapi
flake8
flake8-blind-except
flake8-debugger
flake8-docstrings
flake8-isort
flask
flask-bcrypt
flask-caching
flask-cors
flask-debugtoolbar
flask-login
flask-migrate
flask-sqlalchemy
flask-static-digest
flask-wtf
flatbuffers
fonttools
frozenlist
fsspec
future
gast
gevent
gitdb
gitpython
google-auth
google-auth-oauthlib
google-pasta
greenlet
grpcio
gunicorn
h11
h5py
icu
idna
importlib-metadata
iniconfig
ipykernel
ipython
ipython_genutils
ipywidgets
isort
itsdangerous
jedi
jinja2
joblib
jsonpath-ng
jsonschema
jsonschema-specifications
jupyter_client
jupyter_core
jupyter_server
jupyterlab-widgets
jupyterlab_pygments
keras
kiwisolver
levenshtein
libclang
libcxx
libffi
libiconv
libsodium
libxml2
libxslt
locket
lxml
mako
markdown
markdown-it-py
markupsafe
marshmallow
matplotlib
matplotlib-inline
mccabe
mdurl
metaphone
mistune
ml-dtypes
multidict
mypy-extensions
nbclassic
nbclient
nbconvert
nbformat
ncurses
nest-asyncio
nltk
notebook
notebook-shim
numpy
oauthlib
openssl
opt-einsum
packaging
pandas
pandocfilters
parso
partd
pathspec
patsy
pep8-naming
pexpect
pickleshare
pillow
pip
platformdirs
plotly
pluggy
ply
probableparsing
prometheus_client
prompt-toolkit
protobuf
psutil
psycopg2-binary
ptyprocess
pure_eval
py4j
pyarrow
pyasn1
pyasn1-modules
pycodestyle
pycparser
pydantic
pydantic-core
pydeck
pydocstyle
pyflakes
pygments
pympler
pyparsing
pyrsistent
pyspark
pytest
pytest-cov
python
python-crfsuite
python-dateutil
python-dotenv
python-fastjsonschema
python-slugify
python-stdnum
pytz
pytz-deprecation-shim
pyyaml
pyzmq
readline
referencing
regex
requests
requests-oauthlib
retrying
rich
rpds-py
rsa
scikit-learn
scipy
seaborn
send2trash
setuptools
shell
six
smmap
sniffio
snowballstemmer
soupsieve
sqlalchemy
sqlite
stack_data
starlette
statsmodels
streamlit
streamlit-chat
supervisor
tenacity
tensorboard
tensorboard-data-server
tensorflow
tensorflow-estimator
tensorflow-io-gcs-filesystem
tensorflow-macos
termcolor
terminado
testpath
text-unidecode
threadpoolctl
tinycss2
tk
toml
toolz
tornado
tqdm
traitlets
typing-extensions
typing_extensions
tzdata
tzlocal
urllib3
usaddress
uvicorn
validators
varname
waitress
wcwidth
webencodings
webob
websocket-client
webtest
werkzeug
wheel
widgetsnbextension
wordcloud
wrapt
wtforms
xgboost
xz
yarl
zeromq
zipp
zlib
zope-event
zope-interface




